# Generated by Django 2.1.5 on 2019-03-12 05:21

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/calendar/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'AcademicCalendar',
                'verbose_name_plural': 'AcademicCalendar',
            },
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_image', models.ImageField(upload_to='images/affiliation')),
            ],
            options={
                'verbose_name': 'Affiliation',
                'verbose_name_plural': 'Affiliation',
            },
        ),
        migrations.CreateModel(
            name='AicteApprovalLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='files/aicte_approval_letter/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'AICTE Approval Letter',
                'verbose_name_plural': 'AICTE Approval Letters',
            },
        ),
        migrations.CreateModel(
            name='CenterOfExcellence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/center_of_excellence/%Y-%m-%d')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('website_link', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Center Of Excellence',
                'verbose_name_plural': 'Center Of Excellence',
            },
        ),
        migrations.CreateModel(
            name='CollegeAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=2019, max_length=10, verbose_name='year')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('percentage_marks', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name': 'College Award',
                'verbose_name_plural': 'College Awards',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cover_photo', models.ImageField(upload_to='images/conference/%Y-%m-%d')),
                ('content', models.FileField(upload_to='files/conference/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='files/download/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/event/%Y-%m-%d')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/%Y-%m-%d')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(unique=True, upload_to='images/faculty/%Y-%m-%d')),
                ('department', models.CharField(blank=True, max_length=250)),
                ('qualification_ug', models.CharField(blank=True, max_length=250)),
                ('qualification_pg', models.CharField(blank=True, max_length=250)),
                ('qualification_phd', models.CharField(blank=True, max_length=250)),
                ('faculty_pdf', models.FileField(unique=True, upload_to='files/faculty_pdf/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structure',
            },
        ),
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Footer About',
                'verbose_name_plural': 'Footer About',
            },
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Footer Contact',
                'verbose_name_plural': 'Footer Contact',
            },
        ),
        migrations.CreateModel(
            name='FooterRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Footer Related Link',
                'verbose_name_plural': 'Footer Related Links',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/gallery/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/hostel/%Y-%m-%d')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostel',
            },
        ),
        migrations.CreateModel(
            name='ImportantFunctionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Format:XXXX-XXXXXXX', regex='^d{4}([-]*)\\d{7}$')])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number without zero and having 10 numbers', regex='^\\d{10}$')])),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Important Functionary',
                'verbose_name_plural': 'Important Functionaries',
            },
        ),
        migrations.CreateModel(
            name='InfoBooklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Information Booklet',
                'verbose_name_plural': 'Information Booklet',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/infrastructure')),
                ('caption', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructure',
            },
        ),
        migrations.CreateModel(
            name='InternationalJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=250)),
                ('image1', models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d')),
                ('image2', models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d')),
                ('image3', models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d')),
                ('lab_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Lab Section',
                'verbose_name_plural': 'Lab Section',
            },
        ),
        migrations.CreateModel(
            name='LandingPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(unique=True, upload_to='images/landing_slider/%Y-%m-%d')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landing Portion',
                'verbose_name_plural': 'Landing Portion',
            },
        ),
        migrations.CreateModel(
            name='ListOfHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='images/list_of_holidays/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'List Of Holiday',
                'verbose_name_plural': 'List Of Holidays',
            },
        ),
        migrations.CreateModel(
            name='MandatoryDisclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='files/mandatory_disclosure/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Mandatory Disclosure',
                'verbose_name_plural': 'Mandatory Disclosure',
            },
        ),
        migrations.CreateModel(
            name='Mediclaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Mediclaim',
                'verbose_name_plural': 'Mediclaim',
            },
        ),
        migrations.CreateModel(
            name='Naac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='files/naac/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'NAAC',
                'verbose_name_plural': 'NAAC',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, max_length=250)),
                ('file', models.FileField(blank=True, upload_to='files/notification//%Y-%m-%d')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/organization_chart/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Organization Chart',
                'verbose_name_plural': 'Organization Chart',
            },
        ),
        migrations.CreateModel(
            name='OurAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='images/alumni/%Y-%m-%d')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_contact', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Our Alumni ',
                'verbose_name_plural': 'Our Alumni',
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name': 'Placement Record',
                'verbose_name_plural': 'Placement Record',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/principal')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Prinicipal',
            },
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_of_event', models.DateField(default=datetime.date.today)),
                ('recent_event_slider', models.ImageField(unique=True, upload_to='images/recent_event_slider/%Y-%m-%d')),
                ('active', models.BooleanField(default=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Recent Event',
                'verbose_name_plural': 'Recent Events',
            },
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name': 'Recruiters',
                'verbose_name_plural': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='RefundNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Refund Norm',
                'verbose_name_plural': 'Refund Norm',
            },
        ),
        migrations.CreateModel(
            name='ResearchAndIndustrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/social_responsibility/%Y-%m-%d')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Social Responsibility',
                'verbose_name_plural': 'Social Responsibility',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/social_responsibility/%Y-%m-%d')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Society',
                'verbose_name_plural': 'Society',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(unique=True, upload_to='images/testimonial/%Y-%m-%d')),
                ('testimonial_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial ',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('section', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/timetable/%Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Time Table',
                'verbose_name_plural': 'Time Tables',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlacementDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/placement')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'T & P Department',
                'verbose_name_plural': 'T & P Department',
            },
        ),
        migrations.CreateModel(
            name='UniversityAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=2019, max_length=10, verbose_name='year')),
                ('name', models.CharField(max_length=255)),
                ('univ_position', models.IntegerField()),
                ('percentage_marks', models.DecimalField(decimal_places=3, max_digits=6)),
                ('medal', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'University Award',
                'verbose_name_plural': 'University Awards',
            },
        ),
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', ckeditor_uploader.fields.RichTextUploadingField()),
                ('mission', ckeditor_uploader.fields.RichTextUploadingField()),
                ('policy', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Vision And Mission',
                'verbose_name_plural': 'Vision And Mission',
            },
        ),
    ]
