# Generated by Django 2.1.1 on 2018-09-26 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=30)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_of_field', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='RecentEventSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_event_slider', models.ImageField(unique=True, upload_to='images/recent_event_slider/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('recent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RecentEvent')),
            ],
        ),
    ]
