# Generated by Django 2.1.1 on 2018-09-27 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recenteventslider',
            name='recent_event',
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='date_of_field',
            new_name='date_of_event',
        ),
        migrations.AddField(
            model_name='recentevent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recentevent',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recentevent',
            name='recent_event_slider',
            field=models.ImageField(default=django.utils.timezone.now, unique=True, upload_to='images/recent_event_slider/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecentEventSlider',
        ),
    ]
