# Generated by Django 3.0.2 on 2020-01-24 05:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200124_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
