# Generated by Django 2.1.5 on 2020-01-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200124_0304'),
        ('core', '0003_affiliation_content'),
    ]

    operations = [
    ]
