# Generated by Django 2.1.1 on 2018-09-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landingportion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingportion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='landingportion',
            name='heading',
        ),
    ]
