# Generated by Django 2.1.1 on 2018-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180927_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(unique=True, upload_to='images/faculty/')),
                ('department', models.CharField(max_length=250)),
                ('date_of_join', models.DateField()),
                ('qualification_ug', models.CharField(max_length=250)),
                ('qualification_pg', models.CharField(max_length=250)),
                ('qualification_phd', models.CharField(max_length=250)),
                ('experience_teaching', models.IntegerField(default=0)),
                ('experience_industry', models.IntegerField(default=0)),
                ('experience_research', models.IntegerField(default=0)),
                ('paper_published_national', models.IntegerField(default=0)),
                ('paper_published_international', models.IntegerField(default=0)),
                ('paper_presented_national', models.IntegerField(default=0)),
                ('paper_presented_international', models.IntegerField(default=0)),
                ('phd_guide_field', models.TextField(null=True)),
                ('phd_guide_university', models.TextField(null=True)),
                ('project_guided_phd', models.TextField(null=True)),
                ('project_guided_master', models.TextField(null=True)),
                ('book_published', models.TextField(null=True)),
                ('professional_membership', models.TextField(null=True)),
                ('consultancy_activity', models.TextField(null=True)),
                ('awards', models.TextField(null=True)),
                ('grants_fetched', models.TextField(null=True)),
                ('interaction_prof_institution', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='footerabout',
            options={'verbose_name': 'Footer About', 'verbose_name_plural': 'Footer About'},
        ),
        migrations.AlterModelOptions(
            name='footercontact',
            options={'verbose_name': 'Footer Contact', 'verbose_name_plural': 'Footer Contact'},
        ),
        migrations.AlterModelOptions(
            name='footerrelatedlinks',
            options={'verbose_name': 'Footer Related Link', 'verbose_name_plural': 'Footer Related Links'},
        ),
        migrations.AlterModelOptions(
            name='landingportion',
            options={'verbose_name': 'Landing Portion', 'verbose_name_plural': 'Landing Portion'},
        ),
        migrations.AlterModelOptions(
            name='recentevent',
            options={'verbose_name': 'Recent Event', 'verbose_name_plural': 'Recent Events'},
        ),
    ]
