# Generated by Django 2.1.1 on 2018-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180928_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='book_published',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='consultancy_activity',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience_industry',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience_research',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience_teaching',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='grants_fetched',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='interaction_prof_institution',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='paper_presented_international',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='paper_presented_national',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='paper_published_international',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='paper_published_national',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_guide_field',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phd_guide_university',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='professional_membership',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='project_guided_master',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='project_guided_phd',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification_pg',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification_phd',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification_ug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
