# Generated by Django 2.1.1 on 2018-10-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faculty_faculty_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_pdf',
            field=models.FileField(blank=True, upload_to='files/faculty_pdf/'),
        ),
    ]
