# Generated by Django 2.1.1 on 2018-10-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181006_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_pdf',
            field=models.FileField(unique=True, upload_to='files/faculty_pdf/'),
        ),
    ]
