# Generated by Django 2.1.1 on 2018-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181006_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(unique=True, upload_to='images/alumni/')),
                ('testimonial_message', models.TextField()),
            ],
        ),
    ]
