# Generated by Django 2.1.1 on 2018-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181006_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerrelatedlinks',
            name='priority',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
