# Generated by Django 2.1.1 on 2018-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=250)),
                ('image1', models.ImageField(unique=True, upload_to='images/labs/')),
                ('image2', models.ImageField(unique=True, upload_to='images/labs/')),
                ('image3', models.ImageField(unique=True, upload_to='images/labs/')),
                ('lab_description', models.TextField()),
            ],
        ),
    ]
