# Generated by Django 2.1.1 on 2018-10-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_labsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentevent',
            old_name='date_of_event',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='recent_event_slider',
            new_name='event_pic',
        ),
        migrations.RemoveField(
            model_name='recentevent',
            name='caption',
        ),
    ]
