# Generated by Django 2.1.1 on 2018-10-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181008_1812'),
        ('core', '0010_footerrelatedlinks_priority'),
    ]

    operations = [
    ]
