# Generated by Django 2.1.1 on 2018-10-09 01:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20181009_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/gallery')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='ImportantFunctionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Format:XXXX-XXXXXXX', regex='^d{4}([-]*)\\d{7}$')])),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number without zero and having 10 numbers', regex='^\\d{10}$')])),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Important Functionary',
                'verbose_name_plural': 'Important Functionaries',
            },
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_chart', models.ImageField(upload_to='images/organization_chart')),
            ],
            options={
                'verbose_name': 'Organization Chart',
                'verbose_name_plural': 'Organization Chart',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/principal')),
                ('messege', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='event_date',
            new_name='date_of_event',
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recentevent',
            old_name='event_pic',
            new_name='recent_event_slider',
        ),
        migrations.AddField(
            model_name='recentevent',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
