# Generated by Django 2.1.1 on 2018-10-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181009_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationchart',
            old_name='organization_chart',
            new_name='image',
        ),
    ]
