# Generated by Django 2.1.1 on 2018-12-06 14:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181009_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.RenameField(
            model_name='principal',
            old_name='messege',
            new_name='message',
        ),
    ]
