# Generated by Django 2.1.1 on 2018-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181206_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionandmission',
            name='content',
        ),
        migrations.AddField(
            model_name='visionandmission',
            name='text',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
