# Generated by Django 2.1.1 on 2018-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181206_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionandmission',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
