# Generated by Django 2.1.1 on 2018-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='images',
            field=models.ImageField(upload_to='images/event/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_pdf',
            field=models.FileField(unique=True, upload_to='files/faculty_pdf/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/faculty/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(upload_to='images/gallery/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image1',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image2',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image3',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='landingportion',
            name='slider',
            field=models.ImageField(unique=True, upload_to='images/landing_slider/%Y-%m-%d--%H:%M:%S '),
        ),
        migrations.AlterField(
            model_name='organizationchart',
            name='image',
            field=models.ImageField(upload_to='images/organization_chart/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(upload_to='images/principal%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='recentevent',
            name='recent_event_slider',
            field=models.ImageField(unique=True, upload_to='images/recent_event_slider/%Y-%m-%d--%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/alumni/%Y-%m-%d--%H:%M:%S'),
        ),
    ]
