# Generated by Django 2.1.1 on 2018-12-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181206_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(upload_to='images/principal/%Y-%m-%d--%H:%M:%S'),
        ),
    ]
