# Generated by Django 2.1.1 on 2018-12-06 14:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181206_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionandmission',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
