# Generated by Django 2.1.1 on 2018-12-06 15:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181206_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionandmission',
            name='text',
        ),
        migrations.AddField(
            model_name='visionandmission',
            name='vision',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
        ),
    ]
