# Generated by Django 2.1.1 on 2018-12-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20181206_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionandmission',
            options={'verbose_name': 'Vision And Mission'},
        ),
    ]
