# Generated by Django 2.1.1 on 2018-12-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181206_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionandmission',
            options={'verbose_name': 'Vision And Mission', 'verbose_name_plural': 'Vision And Mission'},
        ),
    ]
