# Generated by Django 2.1.1 on 2018-12-06 19:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181206_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Principal', 'verbose_name_plural': 'Prinicipal'},
        ),
        migrations.AlterField(
            model_name='principal',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
