# Generated by Django 2.1.1 on 2018-12-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_infrastructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'verbose_name': 'Infrastructure', 'verbose_name_plural': 'Infrastructure'},
        ),
    ]
