# Generated by Django 2.1.1 on 2018-12-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181207_0326'),
        ('core', '0019_auto_20181206_1206'),
    ]

    operations = [
    ]
