# Generated by Django 2.1.1 on 2018-12-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181207_0338'),
        ('core', '0029_merge_20181207_0346'),
    ]

    operations = [
    ]
