# Generated by Django 2.1.1 on 2018-12-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20181207_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterOfExcellence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/center_of_excellence/%Y-%m-%d--%H:%M:%S')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='files/conference_pdf/%Y-%m-%d--%H:%M:%S')),
            ],
        ),
    ]
