# Generated by Django 2.1.1 on 2018-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_centerofexcellence_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cover_photo',
            field=models.ImageField(default='https://www.google.co.in/imgres?imgurl=https%3A%2F%2Fimages.pexels.com%2Fphotos%2F248797%2Fpexels-photo-248797.jpeg%3Fauto%3Dcompress%26cs%3Dtinysrgb%26h%3D350&imgrefurl=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Fnature%2F&docid=ShwNVOdFBcmkxM&tbnid=0BGSuulMzOpmDM%3A&vet=10ahUKEwi8gPmrlo3fAhXZXCsKHb8NBSAQMwhqKAAwAA..i&w=875&h=350&bih=638&biw=1307&q=images&ved=0ahUKEwi8gPmrlo3fAhXZXCsKHb8NBSAQMwhqKAAwAA&iact=mrc&uact=8', upload_to='images/conference/%Y-%m-%d--%H:%M:%S'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='content',
            field=models.FileField(upload_to='files/conference/%Y-%m-%d--%H:%M:%S'),
        ),
    ]
