# Generated by Django 2.1.1 on 2018-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_aicteapprovalletter_download_listofholiday_mandatorydisclosure_naac'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='files/admission_process/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='files/fee_structure/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBooklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='files/info_booklet/%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='RefundNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='files/refund_norm/%Y-%m-%d')),
            ],
        ),
        migrations.AlterField(
            model_name='aicteapprovalletter',
            name='content',
            field=models.FileField(upload_to='files/aicte_approval_letter/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='logo',
            field=models.ImageField(upload_to='images/center_of_excellence/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='content',
            field=models.FileField(upload_to='files/conference/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='cover_photo',
            field=models.ImageField(upload_to='images/conference/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='images',
            field=models.ImageField(upload_to='images/event/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_pdf',
            field=models.FileField(unique=True, upload_to='files/faculty_pdf/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/faculty/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(upload_to='images/gallery/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image1',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image2',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='image3',
            field=models.ImageField(unique=True, upload_to='images/labs/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='landingportion',
            name='slider',
            field=models.ImageField(unique=True, upload_to='images/landing_slider/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='listofholiday',
            name='content',
            field=models.FileField(upload_to='files/list_of_holidays/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='mandatorydisclosure',
            name='content',
            field=models.FileField(upload_to='files/mandatory_disclosure/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='naac',
            name='content',
            field=models.FileField(upload_to='files/naac/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='organizationchart',
            name='image',
            field=models.ImageField(upload_to='images/organization_chart/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='recentevent',
            name='recent_event_slider',
            field=models.ImageField(unique=True, upload_to='images/recent_event_slider/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/alumni/%Y-%m-%d'),
        ),
    ]
