# Generated by Django 2.1.1 on 2018-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20181207_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/calender/%Y-%m-%d')),
            ],
            options={
                'verbose_name_plural': 'AcademicCalender',
                'verbose_name': 'AcademicCalender',
            },
        ),
    ]
