# Generated by Django 2.1.1 on 2018-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_academiccalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('section', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/timetable/%Y-%m-%d')),
            ],
        ),
    ]
