# Generated by Django 2.1.1 on 2018-12-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20181209_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Academic Awards',
                'verbose_name': 'Academic Award',
            },
        ),
        migrations.CreateModel(
            name='UniversityAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('univ_position', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('percentage_marks', models.IntegerField()),
                ('medal', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='awards',
            name='university_awards_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UniversityAwards'),
        ),
    ]
