# Generated by Django 2.1.1 on 2018-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20181209_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_pdf', models.FileField(upload_to='files/affiliation')),
            ],
            options={
                'verbose_name_plural': 'Affiliation',
                'verbose_name': 'Affiliation',
            },
        ),
        migrations.RemoveField(
            model_name='awards',
            name='university_awards_session',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='UniversityAwards',
        ),
    ]
