# Generated by Django 2.1.1 on 2018-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20181209_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='affiliation_pdf',
            field=models.ImageField(upload_to='images/affiliation'),
        ),
    ]
