# Generated by Django 2.1.1 on 2018-12-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_awards_universityawards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='university_awards_session',
            new_name='uni_session',
        ),
    ]
