# Generated by Django 2.1.1 on 2018-12-10 03:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20181209_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='images/alumni/%Y-%m-%d')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Our Alumni ',
                'verbose_name_plural': 'Our Alumni',
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name': 'Placement Record',
                'verbose_name_plural': 'Placement Record',
            },
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name': 'Recruiters',
                'verbose_name_plural': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlacementDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/placement')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'T & P Department',
                'verbose_name_plural': 'T & P Department',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial ', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/testimonial/%Y-%m-%d'),
        ),
    ]
