# Generated by Django 2.1.1 on 2019-01-03 14:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20181209_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='images/alumni/%Y-%m-%d')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Our Alumni',
                'verbose_name': 'Our Alumni ',
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name_plural': 'Placement Record',
                'verbose_name': 'Placement Record',
            },
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/placement')),
            ],
            options={
                'verbose_name_plural': 'Recruiters',
                'verbose_name': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlacementDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/placement')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'T & P Department',
                'verbose_name': 'T & P Department',
            },
        ),
        migrations.AlterModelOptions(
            name='collegeawards',
            options={'verbose_name': 'College Award', 'verbose_name_plural': 'College Awards'},
        ),
        migrations.AlterModelOptions(
            name='labsection',
            options={'verbose_name': 'Lab Section', 'verbose_name_plural': 'Lab Section'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Principal', 'verbose_name_plural': 'Principal'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial ', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Time Table', 'verbose_name_plural': 'Time Tables'},
        ),
        migrations.AlterModelOptions(
            name='universityawards',
            options={'verbose_name': 'University Award', 'verbose_name_plural': 'University Awards'},
        ),
        migrations.RemoveField(
            model_name='collegeawards',
            name='colg_session',
        ),
        migrations.RemoveField(
            model_name='universityawards',
            name='uni_session',
        ),
        migrations.AddField(
            model_name='collegeawards',
            name='session',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='universityawards',
            name='session',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_pic',
            field=models.ImageField(unique=True, upload_to='images/testimonial/%Y-%m-%d'),
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
