# Generated by Django 2.1.1 on 2019-01-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20181210_0359'),
        ('core', '0050_auto_20190103_1410'),
    ]

    operations = [
    ]
