# Generated by Django 2.1.1 on 2019-01-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20190104_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Principal', 'verbose_name_plural': 'Prinicipal'},
        ),
    ]
