# Generated by Django 2.1.1 on 2019-01-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190104_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='centerofexcellence',
            options={'verbose_name': 'Center Of Excellence', 'verbose_name_plural': 'Center Of Excellence'},
        ),
        migrations.RemoveField(
            model_name='collegeawards',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='trainingplacementdepartment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='universityawards',
            name='branch',
        ),
        migrations.AlterField(
            model_name='collegeawards',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AcademicSession'),
        ),
        migrations.AlterField(
            model_name='universityawards',
            name='session',
            field=models.CharField(max_length=255),
        ),
    ]
