# Generated by Django 2.1.1 on 2019-01-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190104_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeawards',
            name='branch',
        ),
    ]
