# Generated by Django 2.1.1 on 2019-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_collegeawards_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeawards',
            name='session',
            field=models.CharField(max_length=255),
        ),
    ]
