# Generated by Django 2.1.1 on 2019-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190104_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityawards',
            name='session',
            field=models.CharField(max_length=255),
        ),
    ]
