# Generated by Django 2.1.1 on 2019-01-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20190104_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityawards',
            name='branch',
        ),
    ]
