# Generated by Django 2.1.1 on 2019-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190125_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(default='www.akgec.ac.in', max_length=250),
        ),
    ]
