# Generated by Django 2.1.1 on 2019-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190127_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicteapprovalletter',
            options={'verbose_name': 'AICTE Approval Letter', 'verbose_name_plural': 'AICTE Approval Letters'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': 'Download', 'verbose_name_plural': 'Downloads'},
        ),
        migrations.AlterModelOptions(
            name='listofholiday',
            options={'verbose_name': 'List Of Holiday', 'verbose_name_plural': 'List Of Holidays'},
        ),
        migrations.AlterModelOptions(
            name='mandatorydisclosure',
            options={'verbose_name': 'Mandatory Disclosure', 'verbose_name_plural': 'Mandatory Disclosure'},
        ),
        migrations.AlterModelOptions(
            name='naac',
            options={'verbose_name': 'NAAC', 'verbose_name_plural': 'NAAC'},
        ),
        migrations.AddField(
            model_name='centerofexcellence',
            name='website_link',
            field=models.URLField(default='akgecskills.in', max_length=250),
        ),
        migrations.AlterField(
            model_name='listofholiday',
            name='content',
            field=models.ImageField(upload_to='images/list_of_holidays/%Y-%m-%d'),
        ),
    ]
