# Generated by Django 2.1.1 on 2019-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20190127_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='content',
            field=models.FileField(default='settings.MEDIA_ROOT/files/faculty_pdf/2019-01-04/0998_Sample_Company_Profile.pdf', upload_to='files/download/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='download',
            name='title',
            field=models.CharField(default='abc', max_length=250),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='website_link',
            field=models.URLField(max_length=250),
        ),
    ]
