# Generated by Django 2.1.1 on 2019-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20190127_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structure'},
        ),
        migrations.AlterModelOptions(
            name='refundnorm',
            options={'verbose_name': 'Refund Norm', 'verbose_name_plural': 'Refund Norm'},
        ),
    ]
