# Generated by Django 2.1.1 on 2019-01-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20190127_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infobooklet',
            options={'verbose_name': 'Information Booklet', 'verbose_name_plural': 'Information Booklet'},
        ),
    ]
