# Generated by Django 2.1.1 on 2019-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190127_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'verbose_name': 'Hostel', 'verbose_name_plural': 'Hostel'},
        ),
        migrations.AlterModelOptions(
            name='mediclaim',
            options={'verbose_name': 'Mediclaim', 'verbose_name_plural': 'Mediclaim'},
        ),
        migrations.AlterModelOptions(
            name='socialresponsibility',
            options={'verbose_name': 'Social Responsibility', 'verbose_name_plural': 'Social Responsibility'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Society', 'verbose_name_plural': 'Society'},
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='FruitAndNut/media/images/affiliation/informal-letter-format-ending-fresh-formal-signature-thinkpawsitive-of.png', upload_to='images/events/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(default='FruitAndNut/media/images/affiliation/informal-letter-format-ending-fresh-formal-signature-thinkpawsitive-of.png', upload_to='images/hostel/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='socialresponsibility',
            name='image',
            field=models.ImageField(default='FruitAndNut/media/images/affiliation/informal-letter-format-ending-fresh-formal-signature-thinkpawsitive-of.png', upload_to='images/social_responsibility/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='society',
            name='image',
            field=models.ImageField(default='FruitAndNut/media/images/affiliation/informal-letter-format-ending-fresh-formal-signature-thinkpawsitive-of.png', upload_to='images/social_responsibility/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='events',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='socialresponsibility',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='society',
            name='content',
            field=models.TextField(),
        ),
    ]
