# Generated by Django 2.1.1 on 2019-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20190128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='images/events/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(upload_to='images/hostel/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='socialresponsibility',
            name='image',
            field=models.ImageField(upload_to='images/social_responsibility/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='society',
            name='image',
            field=models.ImageField(upload_to='images/social_responsibility/%Y-%m-%d'),
        ),
    ]
