# Generated by Django 2.1.1 on 2019-01-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20190130_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(upload_to='files/notification//%Y-%m-%d'),
        ),
    ]
