# Generated by Django 2.1.1 on 2019-01-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20190130_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouralumni',
            name='designation',
            field=models.CharField(default='abc', max_length=255),
        ),
    ]
