# Generated by Django 2.1.1 on 2019-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_ouralumni_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouralumni',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
